version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /tttgame/scripts/clean_files.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /tttgame/scripts/start_server.sh
      timeout: 300
      runas : root
