version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: clean_files.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: kill_port.sh
      timeout: 300
      runas: root
