version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: clean_files.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: execute_npm.sh
      timeout: 300
      runas: root
