version: 0.2

phases:
  build:
    commands:
         - echo "Present Working Directory"
         - pwd 
         - echo "Listing the Files"
         - ls
         - echo $env
         - echo $region
         - echo $user
         - echo $id
artifacts:
    files:
      - '**/*'
