version: 2.1
workflows:
  deploy_application:
    - aws-code-deploy/deploy:      
        application-name: MyReactApp
        deployment-group: MyReactApp-DG
        service-role-arn: aws:iam::760603953831:role/CodeDeployServiceRole2
        bundle-bucket: codefrontbucket
        bundle-key: ReactApp
        
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.11
