version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.11
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: ReactApp1002
          deployment-group: ReactApp1002-DG
          service-role-arn: arn:aws:iam::760603953831:role/CodeDeployServiceRole2
          bundle-bucket: codefrontbucket
          bundle-key: ReactApp
