version: 2.1
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:      
          application-name: MyReactApp
          deployment-group: MyReactApp-DG
          service-role-arn: aws:iam::760603953831:role/CodeDeployServiceRole2
          bundle-bucket: codefrontbucket
          bundle-key: ReactApp
      - build: 
          docker: 
            - image: circleci/node:8
          steps:
            - checkout
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run: 
                name: Setup Dependencies
                commands: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.11
